package:
  name: ccpi-reconstruction
  version: {{ environ['CIL_VERSION'] }}


build:
  preserve_egg_dir: False
  script_env:
    - CIL_VERSION   
#  number: 0
  
requirements:
  build:
    - python
    - numpy
    - setuptools
    - boost ==1.64.0	
    - boost-cpp ==1.64.0
    - cython
    - libtiff

  run:
    - python
    - numpy
    - boost ==1.64
    - libtiff
    - pillow

	
about:
  home: http://www.ccpi.ac.uk
  license:  BSD license
  summary: 'CCPi Toolbox'
