package:
  name: cil_reconstruction
  version: {{ environ['CIL_VERSION'] }}


build:
  preserve_egg_dir: False
  script_env:
    - CIL_VERSION   
#  number: 0
    
requirements:
  build:
    - boost
    - boost-cpp
    - python
    - cmake >=3.1
    - vc 14 # [win and py35] 
    - vc 14 # [win and py36] 
    - vc 9  # [win and py27]
    - libtiff    
    - numpy

  run:
    - boost
    - libtiff
    - vc 14 # [win and py35]
    - vc 9  # [win and py27]
    - python
    - numpy
	
about:
  home: http://www.ccpi.ac.uk
  license:  Apache v 2.0
  summary: 'CCPi Toolbox'
