package:
  name: cil_reconstruction
  version: {{ environ['CIL_VERSION'] }}


build:
  preserve_egg_dir: False
  script_env:
    - CIL_VERSION   
#  number: 0
  
build:
  features:
    - vc14  # [win and py35]
  
  
requirements:
  build:
    - boost ==1.64.0	
    - boost-cpp ==1.64.0 
#    - toolchain
    - python 3.5        
    - cmake >=3.1
#    - zlib 1.2.11
    - vc14  # [win and py35] 
    - libtiff    
    - numpy

  run:
    - boost ==1.64.0
    - libtiff
    - vc14 # [win]
    - python 3.5
    - numpy
	
about:
  home: http://www.ccpi.ac.uk
  license:  BSD license
  summary: 'CCPi Toolbox'
