package:
  name: ccpi-reconstruction
  version: "0.9"


build:
  preserve_egg_dir: False
#  number: 0
  
requirements:
  build:
    - python
    - numpy
    - setuptools
    - boost ==1.64	
    - boost-cpp ==1.64
    - cython

  run:
    - python
    - numpy
    - boost ==1.64

	
about:
  home: http://www.ccpi.ac.uk
  license:  BSD license
  summary: 'CCPi Toolbox'
