package:
  name: ccpi
  version: "0.1"


build:
  preserve_egg_dir: yes
#  number: 0
  
requirements:
  build:
    - python
    - numpy
    - setuptools
    - boost ==1.61	
    - boost-cpp ==1.61
    - cython

  run:
    - python
    - numpy
    - boost ==1.61

	
about:
  home: http://www.ccpi.ac.uk
  license:  BSD license
  summary: 'CCPi Toolbox'